---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-admin-cluster-role
  annotations:
    kapp.k14s.io/change-group: serviceaccount
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-admin-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: platform-sa
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-sa
  namespace: default
  annotations:
    kapp.k14s.io/change-group: serviceaccount
