---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative-serving
  annotations:
    kapp.k14s.io/change-group: "cloud.thomasvitale.com/knative-serving"
    kapp.k14s.io/change-rule: "upsert after upserting cloud.thomasvitale.com/contour"
spec:
  serviceAccountName: platform-sa
  syncPeriod: 1m
  packageRef:
    refName: knative-serving.community.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0
  values:
    - secretRef:
        name: knative-serving-values
---
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
stringData:
  values.yml: |
    ---
    domain:
      type: real
      name: <your_dns_name>
    tls:
      certmanager:
        clusterissuer: letsencrypt-staging
