apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: level-1-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: KeyPressedEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: level-1
    uri: /KeyPressedEvent

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: level-1-completed-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: LevelCompletedEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye