#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-frontend-config
  namespace: #@ data.values.namespace
data:
  application.yml: |
    server:
      shutdown:
        graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-frontend
  namespace: #@ data.values.namespace
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: game-frontend
          image: ghcr.io/thomasvitale/fmtok8s-game-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: 756Mi
              cpu: "0.1"
            limits:
              memory: 756Mi
              cpu: "2"
          volumeMounts:
            - name: game-frontend-config-volume
              mountPath: /opt/config
      volumes:
        - name: game-frontend-config-volume
          configMap:
            name: game-frontend-config
