apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: level-1
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: salaboy/fmtok8s-level-1:0.1.0
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health/liveness
          readinessProbe:
            httpGet:
              path: /health/readiness
          env:
            - name: REDIS_HOST
              value: ""
            - name: REDIS_PASSWORD
              value: ""
