#@ load("@ytt:data", "data")

#@yaml/text-templated-strings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devoxxuk-questions-4-config
  namespace: #@ data.values.namespace
data:
  application.yml: |
    game:
      eventing:
        enabled: true
    server:
      shutdown:
        graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s
      redis:
        host: (@= data.values.redis.host @)
        port: (@= data.values.redis.port @)
        password: (@= data.values.redis.password @)

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: devoxxuk-questions-4
  namespace: #@ data.values.namespace
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/thomasvitale/devoxxuk-question-4:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: "0.1"
            limits:
              memory: 256Mi
              cpu: "2"
          volumeMounts:
            - name: devoxxuk-questions-4-config-volume
              mountPath: /workspace/config
      volumes:
        - name: devoxxuk-questions-4-config-volume
          configMap:
            name: devoxxuk-questions-4-config
