apiVersion: v1
kind: ConfigMap
metadata:
  name: game-frontend-config
data:
  application.yml: |
    server:
      shutdown:
        graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s
