apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    contour:
      enabled: true
  config:
    autoscaler:
      enable-scale-to-zero: "true"
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-http01-issuer
    domain:
      thomasvitale.dev: ""
    features:
      tag-header-based-routing: "Enabled"
      kubernetes.podspec-fieldref: "Enabled"
    network:
      autocreate-cluster-domain-claims: "true"
      autoTLS: Enabled
      ingress-class: "contour.ingress.networking.knative.dev"
  additionalManifests:
    - URL: https://github.com/knative/net-certmanager/releases/download/knative-v1.3.0/release.yaml
