apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: start-level
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: salaboy/start-level:latest
          livenessProbe:
            httpGet:
              path: /health/liveness
          readinessProbe:
            httpGet:
              path: /health/readiness
          env:
            - name: REDIS_HOST
              value: ""
            - name: REDIS_PASSWORD
              value: ""
