apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: game-cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
