apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: salaboy/fmtok8s-game-ui:0.1.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
          env:
            - name: GAME_CONTROLLER_SERVICE
              value: http://game-controller.default.svc.cluster.local
          resources:
            requests:
              memory: 756Mi
              cpu: "0.1"
            limits:
              memory: 756Mi
              cpu: "2"
          volumeMounts:
            - name: game-ui-config-volume
              mountPath: /opt/config
      volumes:
        - name: game-ui-config-volume
          configMap:
            name: game-ui-config
