---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  annotations:
    kapp.k14s.io/change-group: "cloud.thomasvitale.com/contour"
    kapp.k14s.io/change-rule: "upsert after upserting cloud.thomasvitale.com/package-repo"
spec:
  serviceAccountName: platform-sa
  syncPeriod: 1m
  packageRef:
    refName: contour.community.tanzu.vmware.com
    versionSelection:
      constraints: 1.20.1
  values:
    - secretRef:
        name: contour-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
stringData:
  values.yml: |
    ---
    contour:
      logLevel: info
    envoy:
      logLevel: info
      hostPorts:
        enable: true
        http: 80
        https: 443
      service:
        type: ClusterIP
