---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tce-repo
  annotations:
    kapp.k14s.io/change-group: "cloud.thomasvitale.com/package-repo"
spec:
  syncPeriod: 1m
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tce/main:0.12.0
