apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  annotations:
    kapp.k14s.io/change-group: "cloud.thomasvitale.com/knative-eventing"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
  annotations:
    kapp.k14s.io/change-group: "cloud.thomasvitale.com/knative-eventing"
